"""Meaningless message

Revision ID: f0d924a6e7a0
Revises: 
Create Date: 2022-03-17 13:17:54.385913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d924a6e7a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('favicon', sa.String(length=255), nullable=True),
    sa.Column('font', sa.String(length=255), nullable=True),
    sa.Column('linkColor', sa.String(length=255), nullable=True),
    sa.Column('isOpen', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('link1Text', sa.String(length=255), nullable=True),
    sa.Column('link1Url', sa.String(length=2048), nullable=True),
    sa.Column('link2Text', sa.String(length=255), nullable=True),
    sa.Column('link2Url', sa.String(length=2048), nullable=True),
    sa.Column('link3Text', sa.String(length=255), nullable=True),
    sa.Column('link3Url', sa.String(length=2048), nullable=True),
    sa.Column('link4Text', sa.String(length=255), nullable=True),
    sa.Column('link4Url', sa.String(length=2048), nullable=True),
    sa.Column('link5Text', sa.String(length=255), nullable=True),
    sa.Column('link5Url', sa.String(length=2048), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pageId', sa.Integer(), nullable=False),
    sa.Column('imageUrl', sa.String(length=255), nullable=False),
    sa.Column('aspectRatio', sa.String(length=255), nullable=True),
    sa.Column('imageRotation', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('linkText', sa.String(length=255), nullable=True),
    sa.Column('linkUrl', sa.String(length=2048), nullable=True),
    sa.Column('date', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pageId'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('users')
    op.drop_table('pages')
    # ### end Alembic commands ###
