"""Pages and posts

Revision ID: 04cef3ca42a1
Revises: ffdc0a98111c
Create Date: 2022-02-20 10:53:06.772342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04cef3ca42a1'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('link1Text', sa.String(length=255), nullable=True),
    sa.Column('link1Url', sa.String(length=2048), nullable=True),
    sa.Column('link2Text', sa.String(length=255), nullable=True),
    sa.Column('link2Url', sa.String(length=2048), nullable=True),
    sa.Column('link3Text', sa.String(length=255), nullable=True),
    sa.Column('link3Url', sa.String(length=2048), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pageId', sa.Integer(), nullable=False),
    sa.Column('imageUrl', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('linkText', sa.String(length=255), nullable=True),
    sa.Column('linkUrl', sa.String(length=2048), nullable=True),
    sa.Column('date', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imageUrl')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('pages')
    # ### end Alembic commands ###
